# fly.toml app configuration file generated for barry on 2025-11-17T19:51:39+10:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'barry'
primary_region = 'syd'

[build]
  dockerfile = "Dockerfile"
  [build.args]
    GO_VERSION = '1'

[env]
  PORT = '8080'
  HOST = "https://barry.fly.dev"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 8080
  min_machines_running = 0
  processes = [ "app" ]

[[vm]]
  size = 'shared-cpu-1x'
